package app.tryst.ui.common

import app.tryst.data.db.entity.Practice

/**
 * Maps practices to emoji and picks the single "headline" practice for an encounter (the most
 * notable one performed or received), used for the card badge. Approximate by design.
 */
object PracticeVisuals {

    fun primaryPractice(performed: Set<Practice>?, received: Set<Practice>?): Practice? {
        val all = (performed ?: emptySet()) + (received ?: emptySet())
        return PRIORITY.firstOrNull { it in all }
    }

    fun emoji(practice: Practice?): String = practice?.let { EMOJI[it] } ?: FALLBACK

    private const val FALLBACK = "❤️‍🔥"

    /** Most "headline" first; the first match in an encounter's practices wins. Includes every value. */
    private val PRIORITY = listOf(
        Practice.DOUBLE_PENETRATION,
        Practice.FISTING,
        Practice.PEGGING,
        Practice.ANAL,
        Practice.VAGINAL,
        Practice.STRAP_ON,
        Practice.PROSTATE_MASSAGE,
        Practice.SIXTY_NINE,
        Practice.DEEP_THROAT,
        Practice.ORAL,
        Practice.RIMMING,
        Practice.FACE_SITTING,
        Practice.SQUIRTING,
        Practice.CREAMPIE,
        Practice.ANAL_CREAMPIE,
        Practice.FACIAL,
        Practice.CREAMPIE_EATING,
        Practice.CUM_SWAPPING,
        Practice.CUM_KISSING,
        Practice.CUM_PLAY,
        Practice.SWALLOWING,
        Practice.HANDJOB,
        Practice.FINGERING,
        Practice.MANUAL,
        Practice.MUTUAL_MASTURBATION,
        Practice.MASTURBATION,
        Practice.TOYS,
        Practice.FROTTAGE,
        Practice.GRINDING,
        Practice.THREESOME,
        Practice.GROUP_SEX,
        Practice.SWINGING,
        Practice.DOMINATION,
        Practice.SUBMISSION,
        Practice.BONDAGE,
        Practice.RESTRAINTS,
        Practice.IMPACT_PLAY,
        Practice.FLOGGING,
        Practice.SPANKING,
        Practice.CHOKING,
        Practice.HAIR_PULLING,
        Practice.GAGGING,
        Practice.BLINDFOLD,
        Practice.ORGASM_CONTROL,
        Practice.EDGING,
        Practice.NIPPLE_PLAY,
        Practice.BREAST_PLAY,
        Practice.WAX_PLAY,
        Practice.TEMPERATURE_PLAY,
        Practice.SENSORY_PLAY,
        Practice.FOOT_PLAY,
        Practice.TANTRIC,
        Practice.MASSAGE,
        Practice.ROLEPLAY,
        Practice.COSTUME_PLAY,
        Practice.DIRTY_TALK,
        Practice.QUICKIE,
        Practice.SHOWER_SEX,
        Practice.OUTDOOR,
        Practice.PUBLIC,
        Practice.VOYEURISM,
        Practice.EXHIBITIONISM,
        Practice.WATERSPORTS,
        Practice.PHONE_SEX,
        Practice.SEXTING,
        Practice.VIDEO_SEX,
        Practice.MAKING_OUT,
        Practice.KISSING,
        Practice.AFTERCARE,
        Practice.CUDDLING,
        Practice.OTHER,
    )

    private val EMOJI = mapOf(
        Practice.KISSING to "💋",
        Practice.MAKING_OUT to "😘",
        Practice.ORAL to "👅",
        Practice.SIXTY_NINE to "♋",
        Practice.DEEP_THROAT to "👅",
        Practice.RIMMING to "🍑",
        Practice.MANUAL to "✋",
        Practice.FINGERING to "👆",
        Practice.HANDJOB to "✊",
        Practice.VAGINAL to "🍆",
        Practice.ANAL to "🍑",
        Practice.DOUBLE_PENETRATION to "✌️",
        Practice.PEGGING to "🍆",
        Practice.FISTING to "🤜",
        Practice.PROSTATE_MASSAGE to "🍑",
        Practice.TOYS to "🔌",
        Practice.STRAP_ON to "🍆",
        Practice.MUTUAL_MASTURBATION to "🙌",
        Practice.MASTURBATION to "✊",
        Practice.FROTTAGE to "🤼",
        Practice.GRINDING to "🪩",
        Practice.NIPPLE_PLAY to "🤏",
        Practice.MASSAGE to "💆",
        Practice.TANTRIC to "🧘",
        Practice.THREESOME to "👯",
        Practice.GROUP_SEX to "👥",
        Practice.SWINGING to "🔄",
        Practice.DOMINATION to "😈",
        Practice.SUBMISSION to "🙇",
        Practice.BONDAGE to "⛓️",
        Practice.IMPACT_PLAY to "🏓",
        Practice.SPANKING to "👋",
        Practice.FLOGGING to "🪢",
        Practice.CHOKING to "🫦",
        Practice.HAIR_PULLING to "💇",
        Practice.GAGGING to "🤐",
        Practice.BLINDFOLD to "🙈",
        Practice.RESTRAINTS to "🔗",
        Practice.SENSORY_PLAY to "🪶",
        Practice.WAX_PLAY to "🕯️",
        Practice.TEMPERATURE_PLAY to "🧊",
        Practice.FOOT_PLAY to "🦶",
        Practice.BREAST_PLAY to "🍈",
        Practice.ROLEPLAY to "🎭",
        Practice.COSTUME_PLAY to "👗",
        Practice.DIRTY_TALK to "🗣️",
        Practice.EDGING to "⏳",
        Practice.ORGASM_CONTROL to "🎚️",
        Practice.FACE_SITTING to "🪑",
        Practice.SQUIRTING to "💦",
        Practice.CREAMPIE to "💦",
        Practice.ANAL_CREAMPIE to "💦",
        Practice.CREAMPIE_EATING to "👅",
        Practice.FACIAL to "💦",
        Practice.CUM_KISSING to "💋",
        Practice.CUM_SWAPPING to "💋",
        Practice.CUM_PLAY to "💦",
        Practice.SWALLOWING to "😋",
        Practice.QUICKIE to "⚡",
        Practice.SHOWER_SEX to "🚿",
        Practice.OUTDOOR to "🌳",
        Practice.PUBLIC to "🏙️",
        Practice.VOYEURISM to "👀",
        Practice.EXHIBITIONISM to "🪟",
        Practice.WATERSPORTS to "💧",
        Practice.PHONE_SEX to "📞",
        Practice.SEXTING to "📱",
        Practice.VIDEO_SEX to "📹",
        Practice.AFTERCARE to "🫂",
        Practice.CUDDLING to "🫂",
        Practice.OTHER to "❤️‍🔥",
    )
}
